# Generated by Django 5.0.6 on 2024-06-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='profiles/'),
        ),
    ]
