# Generated by Django 5.0.6 on 2024-06-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_person_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
